# configs/train/pretrain.yaml
resume:           "ckpts/tune_upscaler_encdec/checkpoint-latest.pth"  # If not set will not resume from a checkpoint.
resume_optimizer: true  # Recommend to use a new optimizer if you are loading a checkpoint saved during training mode.


# Training settings:
epochs:          300
warmup_epochs:   30
accum_iter:      1
batch_size:      16
num_workers:     10
pin_mem:         false
weight_decay:    0.05
lr:              null  # will be computed automatically if not set
blr:             1e-3  # base learning rate
min_lr:          1e-4  # minimum learning rate
start_epoch:     0  # start epoch
