# configs/train/pretrain.yaml
# W&B/checkpoint settings
resume:           null  # If not set will not resume from a checkpoint.
resume_optimizer: false  # Recommend to use a new optimizer if you are loading a checkpoint saved during training mode.


# Training settings:
epochs:          500
warmup_epochs:   100
accum_iter:      1
batch_size:      32
num_workers:     10
pin_mem:         false
weight_decay:    0.05
lr:              null  # will be computed automatically if not set
blr:             1e-3  # base learning rate
min_lr:          0.0  # minimum learning rate
start_epoch:     0  # start epoch
full_mae_loss_coeff:   1
btnk_mae_loss_coeff:   1